export const currency = [
  { id: 1, name: "USD United States Dollar" },
  { id: 2, name: "EUR European Euro" },
  { id: 3, name: "GBP Pound Sterling" },
  { id: 4, name: "AED UAE Dirham" },
  { id: 5, name: "AFN Afghan Afghani" },
  { id: 6, name: "ALL Albanian Lek" },
  { id: 7, name: "AMD Armenian Dram" },
  { id: 8, name: "ANG Netherlands Antillean Guilder" },
  { id: 9, name: "AOA Angolan Kwanza" },
  { id: 10, name: "ARS Argentine Peso" },
  { id: 11, name: "AUD Australian Dollar" },
  { id: 12, name: "AWG Aruban Florin" },
  { id: 13, name: "AZN Azerbaijan Manat" },
  { id: 14, name: "BAM Bosnia and Herzegovina Convertible Mark" },
  { id: 15, name: "BBD Barbadian Dollar" },
  { id: 16, name: "BDT Bangladeshi Taka" },
  { id: 17, name: "BGN Bulgarian Lev" },
  { id: 18, name: "BHD Bahraini Dinar" },
  { id: 19, name: "BIF Burundi Franc" },
  { id: 20, name: "BMD Bermudian Dollar" },
  { id: 21, name: "BND Brunei Dollar" },
  { id: 22, name: "BOB Bolivian Boliviano" },
  { id: 23, name: "BRL Brazilian Real" },
  { id: 24, name: "BSD Bahamian Dollar" },
  { id: 25, name: "BTN Bhutanese Ngultrum" },
  { id: 26, name: "BWP Botswana Pula" },
  { id: 27, name: "BYN Belarusian Ruble" },
  { id: 28, name: "BZD Belize Dollar" },
  { id: 29, name: "CAD Canadian Dollar" },
  { id: 30, name: "CDF Congolese Franc" },
  { id: 31, name: "CHF Swiss Franc" },
  { id: 32, name: "CLP Chilean Peso" },
  { id: 33, name: "CNY Chinese Yuan Renminbi" },
  { id: 34, name: "COP Colombian Peso" },
  { id: 35, name: "CRC Costa Rican Colon" },
  { id: 36, name: "CUP Cuban Peso" },
  { id: 37, name: "CVE Cabo Verdean Escudo" },
  { id: 38, name: "CZK Czech Koruna" },
  { id: 39, name: "DJF Djiboutian Franc" },
  { id: 40, name: "DKK Danish Krone" },
  { id: 41, name: "DOP Dominican Peso" },
  { id: 42, name: "DZD Algerian Dinar" },
  { id: 43, name: "EGP Egyptian Pound" },
  { id: 44, name: "ERN Eritrean Nakfa" },
  { id: 45, name: "ETB Ethiopian Birr" },
  { id: 46, name: "FJD Fijian Dollar" },
  { id: 47, name: "FKP Falkland Islands Pound" },
  { id: 48, name: "GEL Georgian Lari" },
  { id: 49, name: "GGP Guernsey Pound" },
  { id: 50, name: "GHS Ghanaian Cedi" },
  { id: 51, name: "GIP Gibraltar Pound" },
  { id: 52, name: "GMD Gambian Dalasi" },
  { id: 53, name: "GNF Guinean Franc" },
  { id: 54, name: "GTQ Guatemalan Quetzal" },
  { id: 55, name: "GYD Guyanese Dollar" },
  { id: 56, name: "HKD Hong Kong Dollar" },
  { id: 57, name: "HNL Honduran Lempira" },
  { id: 58, name: "HRK Croatian Kuna" },
  { id: 59, name: "HTG Haitian Gourde" },
  { id: 60, name: "HUF Hungarian Forint" },
  { id: 61, name: "IDR Indonesian Rupiah" },
  { id: 62, name: "ILS Israeli New Shekel" },
  { id: 63, name: "IMP Manx Pound" },
  { id: 64, name: "INR Indian Rupee" },
  { id: 65, name: "IQD Iraqi Dinar" },
  { id: 66, name: "IRR Iranian Rial" },
  { id: 67, name: "ISK Icelandic Krona" },
  { id: 68, name: "JEP Jersey Pound" },
  { id: 69, name: "JMD Jamaican Dollar" },
  { id: 70, name: "JOD Jordanian Dinar" },
  { id: 71, name: "JPY Japanese Yen" },
  { id: 72, name: "KES Kenyan Shilling" },
  { id: 73, name: "KGS Kyrgyzstani Som" },
  { id: 74, name: "KHR Cambodian Riel" },
  { id: 75, name: "KMF Comorian Franc" },
  { id: 76, name: "KPW North Korean Won" },
  { id: 77, name: "KRW South Korean Won" },
  { id: 78, name: "KWD Kuwaiti Dinar" },
  { id: 79, name: "KYD Cayman Islands Dollar" },
  { id: 80, name: "KZT Kazakhstani Tenge" },
  { id: 81, name: "LAK Lao Kip" },
  { id: 82, name: "LBP Lebanese Pound" },
  { id: 83, name: "LKR Sri Lankan Rupee" },
  { id: 84, name: "LRD Liberian Dollar" },
  { id: 85, name: "LSL Lesotho Loti" },
  { id: 86, name: "LYD Libyan Dinar" },
  { id: 87, name: "MAD Moroccan Dirham" },
  { id: 88, name: "MDL Moldovan Leu" },
  { id: 89, name: "MGA Malagasy Ariary" },
  { id: 90, name: "MKD Macedonian Denar" },
  { id: 91, name: "MMK Myanmar Kyat" },
  { id: 92, name: "MNT Mongolian Tugrik" },
  { id: 93, name: "MOP Macanese Pataca" },
  { id: 94, name: "MRU Mauritanian Ouguiya" },
  { id: 95, name: "MUR Mauritian Rupee" },
  { id: 96, name: "MVR Maldivian Rufiyaa" },
  { id: 97, name: "MWK Malawian Kwacha" },
  { id: 98, name: "MXN Mexican Peso" },
  { id: 99, name: "MYR Malaysian Ringgit" },
  { id: 100, name: "MZN Mozambican Metical" },
  { id: 101, name: "NAD Namibian Dollar" },
  { id: 102, name: "NGN Nigerian Naira" },
  { id: 103, name: "NIO Nicaraguan Cordoba" },
  { id: 104, name: "NOK Norwegian Krone" },
  { id: 105, name: "FOK Faroese Krona" },
  { id: 106, name: "NPR Nepalese Rupee" },
  { id: 107, name: "NZD New Zealand Dollar" },
  { id: 108, name: "OMR Omani Rial" },
  { id: 109, name: "PEN Peruvian Sol" },
  { id: 110, name: "PGK Papua New Guinean Kina" },
  { id: 111, name: "PHP Philippine Peso" },
  { id: 112, name: "PKR Pakistani Rupee" },
  { id: 113, name: "PLN Polish Zloty" },
  { id: 114, name: "PYG Paraguayan Guarani" },
  { id: 115, name: "QAR Qatari Riyal" },
  { id: 116, name: "RON Romanian Leu" },
  { id: 117, name: "RSD Serbian Dinar" },
  { id: 118, name: "RUB Russian Ruble" },
  { id: 119, name: "RWF Rwandan Franc" },
  { id: 120, name: "SAR Saudi Arabian Riyal" },
  { id: 121, name: "SBD Solomon Islands Dollar" },
  { id: 122, name: "SCR Seychellois Rupee" },
  { id: 123, name: "SDG Sudanese Pound" },
  { id: 124, name: "SEK Swedish Krona" },
  { id: 125, name: "SGD Singapore Dollar" },
  { id: 126, name: "SHP Saint Helena Pound" },
  { id: 127, name: "SLL Sierra Leonean Leone" },
  { id: 128, name: "SOS Somali Shilling" },
  { id: 129, name: "SRD Surinamese Dollar" },
  { id: 130, name: "SSP South Sudanese Pound" },
  { id: 131, name: "STN Sao Tome and Principe Dobra" },
  { id: 132, name: "SYP Syrian Pound" },
  { id: 133, name: "SZL Swazi Lilangeni" },
  { id: 134, name: "THB Thai Baht" },
  { id: 135, name: "TJS Tajikistani Somoni" },
  { id: 136, name: "TMT Turkmen Manat" },
  { id: 137, name: "TND Tunisian Dinar" },
  { id: 138, name: "TOP Tongan Pa’anga" },
  { id: 139, name: "TRY Turkish Lira" },
  { id: 140, name: "TTD Trinidad and Tobago Dollar" },
  { id: 141, name: "TWD New Taiwan Dollar" },
  { id: 142, name: "TZS Tanzanian Shilling" },
  { id: 143, name: "UAH Ukrainian Hryvnia" },
  { id: 144, name: "UGX Ugandan Shilling" },
  { id: 145, name: "UYU Uruguayan Peso" },
  { id: 146, name: "UZS Uzbekistani Som" },
  { id: 147, name: "VES Venezuelan Bolivar" },
  { id: 148, name: "VND Vietnamese Dong" },
  { id: 149, name: "VUV Vanuatu Vatu" },
  { id: 150, name: "WST Samoan Tala" },
  { id: 151, name: "XAF Central African CFA Franc" },
  { id: 152, name: "XCD East Caribbean Dollar" },
  { id: 153, name: "XDR SDR (Special Drawing Right)" },
  { id: 154, name: "XOF West African CFA Franc" },
  { id: 155, name: "XPF CFP Franc" },
  { id: 156, name: "YER Yemeni Rial" },
  { id: 157, name: "ZAR South African Rand" },
  { id: 158, name: "ZMW Zambian Kwacha" }
];
